#FROM pytorch/pytorch:1.9.0-cuda10.2-cudnn7-runtime AS build_base
#FROM us-docker.pkg.dev/vertex-ai/training/pytorch-gpu.1-9:latest AS build_base
FROM pytorch/pytorch:latest AS build_base

# install dependent packages
RUN apt-get -y update && apt-get install -y --no-install-recommends \
    # for install
    curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# install python packages
WORKDIR /component
COPY requirements.txt ./
RUN pip install -r requirements.txt

# copy base source code and add path into PYTHONPATH
ENV PYTHONPATH $PYTHONPATH:/component/src

# set gpu memory size for pytorch if oom is occured
# ENV PYTORCH_CUDA_ALLOC_CONF max_split_size_mb:100

#
# BUILD AND EXECUTE UNIT TEST
# ------------------------------------------------------------------------------
FROM build_base AS test_runner

# copy test directory and run test
COPY src/ src/
COPY tests/ tests/

# run unit tests
RUN python3 -m unittest

#
# BUILD PRODUCTION IMAGE
# ------------------------------------------------------------------------------
FROM build_base AS production

# apply the cache system, copy codes
COPY src/ src/

# set gpu meemory size for pytorch
ENV PYTORCH_CUDA_ALLOC_CONF max_split_size_mb:50

# execute python code as default entrypoint.
ENTRYPOINT [ "python", "/component/src/trainer.py" ]
