name: trainer
inputs:
  - { name: train_data, type: LocalPath }
  - { name: val_data, type: LocalPath }
  - { name: test_data, type: LocalPath }
  - { name: suffix, type: String }
  - { name: parameters, type: String }
outputs:
  - { name: trained_model, type: Artifact }
implementation:
  container:
    image: ${tagged_name}
    args:
      - { inputPath: train_data }
      - { inputPath: val_data }
      - { inputPath: test_data }
      - { inputValue: suffix }
      - { inputValue: parameters }
      - { outputPath: trained_model }
