name: trainer
inputs:
- {name: train_data_path, type: LocalPath}
- {name: val_data_path, type: LocalPath}
- {name: test_data_path, type: LocalPath}
- {name: suffix, type: String}
- {name: parameters, type: String}
outputs:
- {name: trained_model_dir, type: LocalPath}
implementation:
  container:
    image: ${tagged_name}
    args:
      - {inputPath: train_data_path}
      - {inputPath: val_data_path}
      - {inputPath: test_data_path}
      - {inputValue: suffix}
      - {inputValue: parameters}
      - {outputPath: trained_model_dir}
